version: '3.7'
services:
  web:
    build: .
    command: /bin/sh -c "rm -f /q2/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/q2/
      - ./tmp:/q2/tmp/
  db:
    image: postgres:10.5
    volumes:
      - ./db/data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
